[AlmaLinuxPowerTools]
name=AlmaLinux {releasever} - PowerTools
filename=almalinux.repo
mirror.repo=almalinux/{releasever}/PowerTools/{arch}/os/
mirror.gpgkey=almalinux/RPM-GPG-KEY-AlmaLinux-{releasever}
upstream.repo=https://repo.almalinux.org/almalinux/{releasever}/PowerTools/{arch}/os/
upstream.gpgkey=https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-{releasever}

[AlmaLinuxCRB]
name=AlmaLinux {releasever} - CRB
filename=almalinux.repo
mirror.repo=almalinux/{releasever}/CRB/{arch}/os/
mirror.gpgkey=almalinux/RPM-GPG-KEY-AlmaLinux-{releasever}
upstream.repo=https://repo.almalinux.org/almalinux/{releasever}/CRB/{arch}/os/
upstream.gpgkey=https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-{releasever}

[AlmaLinuxAppStream]
name=AlmaLinux {releasever} - AppStream
filename=almalinux.repo
mirror.repo=almalinux/{releasever}/AppStream/{arch}/os/
mirror.gpgkey=almalinux/RPM-GPG-KEY-AlmaLinux-{releasever}
upstream.repo=https://repo.almalinux.org/almalinux/{releasever}/AppStream/{arch}/os/
upstream.gpgkey=https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-{releasever}

[AlmaLinuxBaseOS]
name=AlmaLinux {releasever} - BaseOS
filename=almalinux.repo
mirror.repo=almalinux/{releasever}/BaseOS/{arch}/os/
mirror.gpgkey=almalinux/RPM-GPG-KEY-AlmaLinux-{releasever}
upstream.repo=https://repo.almalinux.org/almalinux/{releasever}/BaseOS/{arch}/os/
upstream.gpgkey=https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-{releasever}
