[appstream]
name=Red Hat Enterprise Linux {releasever} - AppStream ({arch})
filename=rhel.repo
mirror.repo=rhel/rhel-{releasever}-for-{arch}-appstream-rpms/
mirror.gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
upstream.repo=https://cdn.redhat.com/content/dist/rhel{releasever}/{releasever}/{arch}/appstream/os/
upstream.gpgkey=https://www.redhat.com/security/data/fd431d51.txt

[codeready-builder]
name=Red Hat Enterprise Linux {releasever} - CodeReady Builder ({arch})
filename=rhel.repo
mirror.repo=rhel/codeready-builder-for-rhel-{releasever}-{arch}-rpms/
mirror.gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
upstream.repo=https://cdn.redhat.com/content/dist/rhel{releasever}/{releasever}/{arch}/codeready-builder/os/
upstream.gpgkey=https://www.redhat.com/security/data/fd431d51.txt

[baseos]
name=Red Hat Enterprise Linux {releasever} - BaseOS ({arch})
filename=rhel.repo
mirror.repo=rhel/rhel-{releasever}-for-{arch}-baseos-rpms/
mirror.gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
upstream.repo=https://cdn.redhat.com/content/dist/rhel{releasever}/{releasever}/{arch}/baseos/os/
upstream.gpgkey=https://www.redhat.com/security/data/fd431d51.txt
