/*
 * Copyright 2022 Vinícius Ferrão <vinicius@ferrao.net.br>
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef OPENCATTUS_PRESENTERQUEUESYSTEM_H_
#define OPENCATTUS_PRESENTERQUEUESYSTEM_H_

#include <opencattus/presenter/Presenter.h>

namespace opencattus::presenter {
class PresenterQueueSystem : public Presenter {
private:
    struct Messages {
        static constexpr const auto title = "Queue system settings";
        static constexpr const auto question
            = "Choose a workload manager for compute jobs";
        static constexpr const auto help
            = "Choose the workload manager for the compute nodes. SLURM is "
              "the default HPC scheduler; PBS Professional is available for "
              "sites that standardize on PBS.";

        struct SLURM {
            static constexpr const auto title = "SLURM settings";
            static constexpr const auto question
                = "Enter the SLURM controller settings. The accounting "
                  "storage password will reuse the slurmdbd password.";
            static constexpr const auto help
                = "The partition name is the default queue visible to users. "
                  "Database passwords are generated by default and may be "
                  "overridden when needed.";

            static constexpr const auto partition = "Partition name";
            static constexpr const auto mariadbRootPassword
                = "MariaDB root password";
            static constexpr const auto slurmDBPassword = "slurmdbd password";
        };

        struct PBS {
            static constexpr const auto title = "PBS Professional settings";
            static constexpr const auto question
                = "Select the default execution place for PBS Professional "
                  "jobs";
            static constexpr const auto help
                = "The execution place controls how PBS places jobs on nodes. "
                  "Use the default unless your site has a specific PBS policy.";
        };
    };

public:
    PresenterQueueSystem(
        std::unique_ptr<Cluster>& model, std::unique_ptr<View>& view);
};

};

#endif // OPENCATTUS_PRESENTERQUEUESYSTEM_H_
