set(OPENCATTUS_PACKAGE_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}")
if(PROJECT_VERSION_PATCH GREATER 0)
    set(OPENCATTUS_PACKAGE_VERSION "${PROJECT_VERSION}")
endif()

set(OPENCATTUS_RPM_RELEASE "1" CACHE STRING "RPM package release")
set(OPENCATTUS_DEB_RELEASE "1" CACHE STRING "DEB package release")

set(CPACK_GENERATOR "RPM")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_PROJECT_CONFIG_FILE "${CMAKE_BINARY_DIR}/CPackProjectConfig.cmake")

set(CPACK_PACKAGE_NAME "opencattus")
set(CPACK_PACKAGE_VERSION "${OPENCATTUS_PACKAGE_VERSION}")
set(CPACK_PACKAGE_VENDOR "VersatusHPC")
set(CPACK_PACKAGE_CONTACT "VersatusHPC <vinicius@ferrao.net.br>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OpenCATTUS Installer")
set(CPACK_PACKAGE_DESCRIPTION
        "OpenCATTUS installs and configures an HPC cluster from a single head node.")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/VersatusHPC/opencattus")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")

set(CPACK_MONOLITHIC_INSTALL ON)
set(CPACK_PACKAGING_INSTALL_PREFIX "/")
set(CPACK_STRIP_FILES ON)
set(CPACK_VERBATIM_VARIABLES ON)

set(CPACK_SOURCE_IGNORE_FILES
        "/\\\\.git/"
        "/build[^/]*/"
        "/out/"
        "/\\\\.cache/"
        "\\\\.(rpm|deb|tar\\\\.gz)$")

set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_RPM_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
set(CPACK_RPM_PACKAGE_RELEASE "${OPENCATTUS_RPM_RELEASE}")
set(CPACK_RPM_PACKAGE_RELEASE_DIST ON)
set(CPACK_RPM_PACKAGE_SUMMARY "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
set(CPACK_RPM_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION}")
set(CPACK_RPM_PACKAGE_VENDOR "${CPACK_PACKAGE_VENDOR}")
set(CPACK_RPM_PACKAGE_LICENSE "Apache-2.0")
set(CPACK_RPM_PACKAGE_GROUP "Applications/System")
set(CPACK_RPM_PACKAGE_URL "${CPACK_PACKAGE_HOMEPAGE_URL}")
set(CPACK_RPM_PACKAGE_REQUIRES "newt")
set(CPACK_RPM_PACKAGE_PROVIDES "opencattus-installer = ${CPACK_RPM_PACKAGE_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}%{?dist}")
set(CPACK_RPM_PACKAGE_OBSOLETES "opencattus-installer <= 1.0-1%{?dist}, opencattus-installer-debug <= 1.0-6%{?dist}")
set(CPACK_RPM_PACKAGE_RELOCATABLE OFF)
set(CPACK_PACKAGE_RELOCATABLE OFF)
set(CPACK_RPM_NO_INSTALL_PREFIX_RELOCATION ON)

# Conan-linked builds carry temporary cache RPATH entries. They are harmless for
# the static Conan libraries we consume, but RPM brp checks reject the paths.
set(CPACK_RPM_SPEC_MORE_DEFINE
        "%define __brp_check_rpaths %{nil}
%global _enable_debug_package 0
%global debug_package %{nil}")

set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
set(CPACK_DEBIAN_PACKAGE_RELEASE "${OPENCATTUS_DEB_RELEASE}")
set(CPACK_DEBIAN_PACKAGE_SECTION "admin")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "${CPACK_PACKAGE_HOMEPAGE_URL}")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_PROVIDES "opencattus-installer")
set(CPACK_DEBIAN_PACKAGE_BREAKS "opencattus-installer (<= 1.0-1), opencattus-installer-debug (<= 1.0-6)")
set(CPACK_DEBIAN_PACKAGE_REPLACES "opencattus-installer (<= 1.0-1), opencattus-installer-debug (<= 1.0-6)")

include(CPack)
