# Generate a C++ header that embeds every file in OPENCATTUS_REPOS_DIR
# whose name appears in OPENCATTUS_REPOS_FILES as a raw string literal.
# Invoked via:
#   cmake -DOPENCATTUS_REPOS_DIR=...
#         -DOPENCATTUS_REPOS_FILES="a;b;c"
#         -DOPENCATTUS_OUTPUT=...
#         -P cmake/GenerateEmbeddedRepos.cmake

if(NOT OPENCATTUS_REPOS_DIR)
    message(FATAL_ERROR "OPENCATTUS_REPOS_DIR must be set")
endif()
if(NOT OPENCATTUS_REPOS_FILES)
    message(FATAL_ERROR "OPENCATTUS_REPOS_FILES must be set")
endif()
if(NOT OPENCATTUS_OUTPUT)
    message(FATAL_ERROR "OPENCATTUS_OUTPUT must be set")
endif()

set(_decls "")
set(_entries "")
foreach(_name IN LISTS OPENCATTUS_REPOS_FILES)
    string(MAKE_C_IDENTIFIER "${_name}" _sym)
    set(_path "${OPENCATTUS_REPOS_DIR}/${_name}")
    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "Missing embedded source file: ${_path}")
    endif()
    file(READ "${_path}" _content)
    string(APPEND _decls
        "inline constexpr std::string_view ${_sym} = R\"OCEMB(${_content})OCEMB\";\n")
    string(APPEND _entries "    Entry{ \"${_name}\", ${_sym} },\n")
endforeach()
list(LENGTH OPENCATTUS_REPOS_FILES _count)

set(_header
"// Generated by cmake/GenerateEmbeddedRepos.cmake. Do not edit.
#pragma once

#include <array>
#include <string_view>

namespace opencattus::services::embedded_repos {

struct Entry {
    std::string_view name;
    std::string_view content;
};

${_decls}
inline constexpr std::array<Entry, ${_count}> entries = {{
${_entries}}};

} // namespace opencattus::services::embedded_repos
")

file(WRITE "${OPENCATTUS_OUTPUT}" "${_header}")
